name: Semantic Release

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow when you push a tag starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important for semantic-release to work correctly

    - name: Debug Git State
      run: |
        git status
        git branch
        git log -n 5
        git tag
        echo "Current ref: ${{ github.ref }}"

    - name: Checkout Tag Manually
      run: |
        git fetch --tags --force
        git checkout ${{ github.ref }}
        git describe --tags --always

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-semantic-release

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        semantic-release version
